batch_size: 128
data_root: SCRATCH
dataaug: simple
json_path: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/02_ami-gbif_fine-grained_w-europe_category_map.json
image_folder: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
input_size: 126
num_classes: 636
preprocessing_mode: torch
rescale_size: null
train_data_len: 72188
id_train: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/02_w-europe_train_id.csv 
id_val: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/02_w-europe_val_id.csv
id_test: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/02_w-europe_test_id.csv
ood_val: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/02_w-europe_val_aux.csv 
ood_near: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/02_w-europe_test_ood_local.csv
ood_far: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/05_test_ood_non-local.csv
ood_non_moth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/csv/06_test_ood_non-moth.csv
wandb_entity: moth-ai
wandb_project: osr_posthoc

