network:
  name: dinov2
  vit_name: dinov2_vits14_reg
  num_classes: '@{dataset.num_classes}'
  pretrained: False # In training pipeline:"False"; In testing pipeline:"True"
  num_gpus: '@{num_gpus}'
  checkpoint: none
