unlabeled_dataset:
  name: ami_c-america_trap
  num_classes: 636

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False
  data_dir: /network/scratch/y/yuyan.chen/Panama/28670E4D/crop_output/
  



