name: ami_c-america_oe

dataset:
  name: ami_c-america_oe
  split_names: [train, oe, val, test]
  oe:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
    imglist_pth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/aux_labeled/03_c-america_train_oe_20.txt
    batch_size: 512
    shuffle: True
    interpolation: bilinear
