dataset:
  name: ami_c-america
  num_classes: 10497
  num_closed_set: 2497
  pre_size: 128
  image_size: 126

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
    imglist_pth:  ./data/01_ne-america_train_aux_merged.txt
    batch_size: 128
    len: 7491
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
    imglist_pth: ./data/01_ne-america_val_id.txt
    batch_size: 128
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
    imglist_pth: ./data/01_ne-america_test_id.txt
    batch_size: 128
    shuffle: False

    