dataset:
  name: ami_w-europe
  num_classes: 10603
  num_closed_set: 2603
  pre_size: 128
  image_size: 126

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
    imglist_pth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/aux_labeled/02_w-europe_train_aux_merged_20.txt
    batch_size: 128
    len: 1337125
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
    imglist_pth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/txt/02_w-europe_val_id.txt
    batch_size: 128
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
    imglist_pth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/txt/02_w-europe_test_id.txt
    batch_size: 128
    shuffle: False

    