dataset:
  name: ami_c-america
  num_classes: 636
  max_classes: 2500
  pre_size: 128
  image_size: 126

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [labeled, unlabeled]

  labeled:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
    imglist_pth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/txt/03_c-america_val_id.txt
    batch_size: 128
    input_size: 128
    shuffle: False

  unlabeled:
    dataset_class: ImglistDataset
    data_dir: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
    imglist_pth: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/txt/03_c-america_val_id.txt
    batch_size: 128
    input_size: 128
    shuffle: False


  
  # eval_config_path: configs/datasets/ami/posthoc/c-america.yaml

    