batch_size: 64
cb_beta: 0.9
data_root: SCRATCH
dataaug: randaug
epochs: 5
eval_frequency: 1
freeze_feat_extract_reset_classif: false
json_path: /network/scratch/y/yuyan.chen/ood_benchmark/ami/metadata/03_ami-gbif_fine-grained_c-america_category_map.json
image_folder: /network/scratch/y/yuyan.chen/ami_gbif_train_resized/
input_size: 126
instances_per_cls_json: null
label_smoothing: 0.1
label_transform_json: null
log_frequency: 100
loss: ce
lr: 0.001
lr_scheduler: cosine
model_name: timm_resnet50
model_path: null
model_save_path: # ood_benchmark/ami/classifier/resnet50/
num_classes: 636
optimizer: adamw
preprocessing_mode: torch
random_seed: 42
rescale_size: null
sample_exclude_list: null
train_data_len: 72188
id_train: /home/mila/y/yuyan.chen/projects/BioOOD/data/03_c-america_train_id.csv 
id_val: /home/mila/y/yuyan.chen/projects/BioOOD/data/03_c-america_val_id.csv
id_test: /home/mila/y/yuyan.chen/projects/BioOOD/data/03_c-america_test_id.csv
ood_val: /home/mila/y/yuyan.chen/projects/BioOOD/data/03_c-america_val_ood.csv
ood_near: /home/mila/y/yuyan.chen/projects/BioOOD/data/03_c-america_test_ood_local.csv
ood_far: /home/mila/y/yuyan.chen/projects/BioOOD/data/05_test_ood_non-local.csv
ood_non_moth: /home/mila/y/yuyan.chen/projects/BioOOD/data/06_test_ood_non-moth.csv
use_mixres: false
wandb_entity: #moth-ai
wandb_name: #c-america_resnet50_baseline
wandb_project: #ood_benchmark_classifier
warmup_epochs: 2.0
weight_decay: 0
